apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
  name: ""
spec:
  containerd:
    version: 1.6.x
  ekco:
    version: latest
  kotsadm:
    version: latest
    disableS3: true
  kubernetes:
    version: 1.25.5
  openEBS:
    version: 3.3.x
    isLocalPVEnabled: true
    localPVStorageClassName: default
  prometheus:
    version: 0.60.x
  registry:
    version: 2.8.x
  flannel:
    version: 0.20.x
