apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: wordpress-enterprise
spec:
  chart:
    name: wordpress-enterprise
    chartVersion: 0.1.0
  helmVersion: v3
  useHelmInstall: false
  values:
    isKurl: repl{{ IsKurl }}
    config: 
      exampleDefaultValue: repl{{ ConfigOption "example_default_value" }}
      hiddenValue: repl{{ ConfigOption "hidden_text" }}
